import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { getServerSession } from 'next-auth/next'
import { authOptions } from './config/authOptions'
import logo from '@/public/logo.png'
import Image from 'next/image'
import Button from './login/button'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions)
    return (
        <html lang="en">
            <body className={inter.className + '  text-white'}>
                <div className="container mx-auto">
                    <header className="flex justify-between py-2">
                        <div className="w-2/12 py-2">
                            <Image src={logo} alt="logo" />
                        </div>
                        <nav>
                            <ul className="flex justify-between gap-3 items-center h-full">
                                <li>
                                    <Link href="/">Home</Link>
                                </li>
                                <li>
                                    <Link href="/about">About</Link>
                                </li>
                                <li>
                                    <Link href="/dashboard">Dashboard</Link>
                                </li>

                                <li>
                                    <Link href="/dashboard/pages">Pages</Link>
                                </li>
                                {session && (
                                    <li className="font-bold flex gap-1">
                                        <Image
                                            src={session.user.image}
                                            alt={session.user.name}
                                            width={40}
                                            height={40}
                                            className="rounded-full"
                                        />
                                    </li>
                                )}
                                <li>
                                    <Button session={session} />
                                </li>
                            </ul>
                        </nav>
                    </header>
                    <main className="py-5">{children}</main>
                </div>
            </body>
        </html>
    )
}
